# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Regression tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_call:
  schedule:
    - cron: '26 10 * * *'

jobs:
  regression:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: curl "https://raw.githubusercontent.com/orgrimarr/node-wetransfert-assets/main/big/BigBuckBunny.mp4" -o test/ressources/big/BigBuckBunny.mp4
    - run: npm ci
    - run: npm run build --if-present
    - run: set DEBUG="wetransfert*"
    - run: npm test
